Rails:
  Enabled: true
AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    # Generated files
    - Rakefile
    - bin/*
    - config/application.rb
    - config/boot.rb
    - config/environment.rb
    - config/environments/*
    - config/initializers/assets.rb
    - config/initializers/cookies_serializer.rb
    - config/initializers/devise.rb
    - config/initializers/session_store.rb
    - config/initializers/simple_form_bootstrap.rb
    - config/initializers/simple_form.rb
    - db/schema.rb
    - lib/tasks/cucumber.rake
    - script/cucumber
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - vendor/*
Lint/HandleExceptions:
  Exclude:
    - features/step_definitions/authorisation_steps.rb
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/NestedParenthesizedCalls:
  Enabled: false
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
Performance/RedundantMerge:
  Enabled: false
Style/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/HashSyntax:
  Exclude:
    - lib/tasks/*
Style/PredicateName:
  NamePrefixBlacklist:
    - is_
Style/AndOr:
  EnforcedStyle: conditionals
Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Style/BlockDelimiters:
  EnforcedStyle: semantic
  Exclude:
    - factories/**/*
Metrics/MethodLength:
  Max: 5
  Exclude:
    - db/migrate/*
Style/MultilineMethodCallBraceLayout:
  Enabled: false
Style/MultilineArrayBraceLayout:
  Enabled: false
