defautl: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: newsletter-generator_development

test: &test
  <<: *default
  database: newsletter-generator_test

production:
  <<: *default
  database: newsletter-generator_production

cucumber:
  <<: *test
